name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade -r requirements.txt
          fi
          python -m pip install --upgrade toml

      - name: Check version matches tag
        id: check_version
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          FILE_VERSION=$(python3 -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          if [ "$TAG_VERSION" != "v$FILE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match pyproject.toml version ($FILE_VERSION)."
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check_version.outputs.should_publish == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install build dependencies
        if: steps.check_version.outputs.should_publish == 'true'
        run: python -m pip install --upgrade build

      - name: Build package
        if: steps.check_version.outputs.should_publish == 'true'
        run: python -m build

      - name: Publish to PyPI
        if: steps.check_version.outputs.should_publish == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
